# Use postgres/postgres user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      # TODO: encrypt password
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080